# Generated by Django 5.2.11 on 2026-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='exct_time',
            field=models.CharField(default='5 mins', max_length=255),
        ),
    ]
